### ISSUE TITLE
Connection failure while running  ./run_indexing.sh

### ISSUE THREAD

**Issue by liucijus** [flarebuild/rules_idea#6]
Trying to run ` ./run_indexing.sh` and getting connection failure, am I missing some setup step?
```
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 5c5ed8c9-9c9c-4f60-9de5-abfa93916e75
INFO: Analyzed target //:indexes (123 packages loaded, 3167 targets configured).
INFO: Found 1 target...
ERROR: /home/vaidas/projects/rules_idea/examples/test/common/BUILD.bazel:1:13: IntellijIndexing common/common.ijx failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log, file at /home/vaidas/.cache/bazel/_bazel_vaidas/5c021e50cea8bb825fd0a3a624775fd3/bazel-workers/multiplex-worker-1-IntellijIndexing.log ---8<---8<---
########### UnrecoverableError ###########
io.grpc.StatusException: UNAVAILABLE: io exception
        at io.grpc.Status.asException(Status.java:550)
        at io.grpc.kotlin.ClientCalls$rpcImpl$1$1$1.onClose(ClientCalls.kt:295)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /0.0.0.0:9311
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
io.grpc.StatusException: UNAVAILABLE: io exception
----------------------------
---8<---8<--- End of log ---8<---8<---
Target //:indexes failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 68.370s, Critical Path: 21.36s
INFO: 9 processes: 9 internal.
FAILED: Build did NOT complete successfully

```

**Comment by gleyba** [comment]
Fixe in https://github.com/flarebuild/rules_idea/pull/5
